# vim:fileencoding=utf-8:ft=conf

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "autoconf"
brew "bash"
brew "coreutils"
brew "curl"
brew "exa"
brew "fasd"
brew "fd"
brew "fish"
brew "fzf"
brew "gawk"
brew "git"
brew "gnupg"
brew "hub"
brew "jq"
brew "mas"
brew "neovim", args: ['head']
brew "openssl"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "stow"
brew "tmux"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "brave-browser"
cask "bartender"
cask "dash"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "font-ia-writer-quattro"
cask "font-ibm-plex"
cask "font-jetbrains-mono"
cask "grid-clock"
cask "hammerspoon"
cask "karabiner-elements"
cask "kitty"
cask "toggl-track"
mas "Deliveries", id: 924726344
mas "Drafts", id: 1435957248
mas "MindNode", id: 1289197285
mas "Reeder", id: 1529448980
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
