# use vi keys in search mode
set-window-option -g mode-keys vi
set -g copy-mode-line-numbers hybrid
set -g copy-mode-line-number-style "fg=colour8"
set -g copy-mode-current-line-number-style "fg=colour15,bold"
# emacs key bindings in tmux command prompt (prefix + :) are better than
set -g status-keys emacs

set -g history-limit 50000
set -g display-time 4000

# status bar
set-option -g status-left " #S "
set-option -g status-right "#[default italics]%-l:%M"
set-option -g set-titles on
set-option -g set-titles-string "tmux: #I #W"

# window status (tab selected/unselected)
set-window-option -g window-status-current-format "#[fg=colour7] ■ #I:#W#{?window_zoomed_flag, ,}"
set-window-option -g window-status-format " □ #I:#W"
set-window-option -g window-status-current-style fg="colour15"
set -g status-position "top"
set -g status-style bg="default",fg="colour15",dim
set -g message-style bg="colour0",fg="colour3"
set -g pane-active-border-style fg="colour8"
set -g pane-border-style fg="colour8"
# dim inactive window text
set -g window-style fg=colour15
set -g window-active-style fg=colour7

# refresh 'status-left' and 'status-right' more often
set -g status-interval 5

# terminal compatibility settings
set extended-keys on # allows for meta, ctrl, opt keys, etc.
set extended-keys-format csi-u # matches ghostty
set -g allow-passthrough on
set -g focus-events on
setw -g aggressive-resize on
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
set -ag terminal-overrides ',*:cud1=\E[1B' # redraw?

# Binds
bind-key "P" display-popup -T "#[align=centre,bg=colour10,fg=colour0]#[bold] 📂 Repositories " -E -b rounded -s "bg=default fg=default" -S "bg=default fg=colour10" -w 80% -h 80% "\
  sesh connect \"\$(sesh list -i | gum filter --limit 1 --no-sort --fuzzy --placeholder 'Pick a sesh' --padding 3 --height 50 --prompt='  ')\""
bind-key C-j join-pane

bind-key "O" display-popup -T "#[align=centre,bg=colour10,fg=colour0]#[bold] ⬚ Layout " -E -b rounded -s "bg=default fg=default" -S "bg=default fg=colour10" -w 50% -h 50% "\
  tmux select-layout \"\$(printf '%s\n' even-horizontal even-vertical main-horizontal main-vertical tiled | gum choose --header 'Select layout' --limit 1 --cursor '> ')\""
